cyoa-step1: class.h class.cpp cyoa-step1.cpp
		g++ -o cyoa-step1 -Wall -Werror -pedantic -std=gnu++98 -ggdb3 cyoa-step1.cpp class.cpp
cyoa-step2: class.h class.cpp cyoa-step2.cpp
		g++ -o cyoa-step2 -Wall -Werror -pedantic -std=gnu++98 -ggdb3 cyoa-step2.cpp class.cpp
cyoa-step3: class.h class.cpp cyoa-step3.cpp
		g++ -o cyoa-step3 -Wall -Werror -pedantic -std=gnu++98 -ggdb3 cyoa-step3.cpp class.cpp
cyoa-step4: class.h class.cpp cyoa-step4.cpp
		g++ -o cyoa-step4 -Wall -Werror -pedantic -std=gnu++98 -ggdb3 cyoa-step4.cpp class.cpp
